### ISSUE TITLE
一直处于评论加载中，错误码10403

### ISSUE THREAD

**Issue by lniwn** [cheng-kang/wildfire#12]
#### 怎么了 What

页面一直处于评论加载中，打开开发者工具，发现ns.wilddog.com/v1/lookup?这个接口返回出错，错误码 10403。

#### 如何重现 Reproduce

打开我[博客](https://oaoa.me)任意一篇文章，必现。

#### 其他的话 Other Comment
处理步骤：
- 修改wilddog读写权限为[security_rules.json](https://github.com/cheng-kang/wildfire/blob/master/security_rules.json)
- 安全域名添加
> *.oaoa.me 
*.wilddog.com 
*.wilddogio.com 

仍然无法解决，临时解决方案是暂时关闭了安全域名。

**Comment by mrliaocn** [comment]
我查看了你的博客的域名是：`oaoa.me`，因此有一个猜想，安全域名`*.oaoa.me`也许不包含`oaoa.me`，所以你可以试一试直接把`oaoa.me`添加到安全域名看看。

**Comment by lniwn** [comment]
@mrliaocn 之前试过同时添加*.oaoa.me和oaoa.me没有生效，现在同时添加了下面4个，暂时运行良好：
>*.oaoa.me 
*.wilddog.com 
*.wilddogio.com 
oaoa.me

**Comment by cheng-kang** [comment]
@lniwn 之前在野狗工单提交的问题得到了回复，确认是因为安全域名的问题。

**Comment by cheng-kang** [comment]
解决方法：
1. 请参考  [安全 - 管理应用 - 野狗](https://docs.wilddog.com/console/administer.html#%E5%AE%89%E5%85%A8) 正确配置安全域名。
2. 关闭安全域名选项**（不推荐）**

Solution:
1. Set your authorized domains correctly, reference: [安全 - 管理应用 - 野狗](https://docs.wilddog.com/console/administer.html#%E5%AE%89%E5%85%A8).
2. Deactivate `authorized domain` option.
