### ISSUE TITLE
页面url包含中文导致Edge浏览器一直处于“正在启动 Wildfire……”

### ISSUE THREAD

**Issue by lniwn** [cheng-kang/wildfire#13]
### 怎么了 What

只要文章url包含中文，用Edge浏览器打开就无法启动Wildfire，一直显示“正在启动 Wildfire……”

### 如何重现 Reproduce
Url包含中文的文章无法正常加载评论：
<http://mrliao.cn/2017/12/25/在Hexo.NexT主题中部署Wildfire评论系统/>
<https://oaoa.me/vps/2017/12/为Hexo博客Next主题添加Wildfire评论系统/>
Url不包含中文的文章可以正常加载评论：
<https://oaoa.me/cplusplus/2017/12/Cef-Bug-Fix-List/>

### 其他的话 Other Comment

- Chrome  63.0.3239.84
- Firefox 57.0.2
以上浏览器均能正常加载评论

**Comment by mrliaocn** [comment]
非常感谢你的反馈，这个应该是浏览器兼容的问题。我们将尽快解决！

**Comment by mrliaocn** [comment]
已经确定问题的原因是由于`btoa`函数不支持中文造成的。正在修复，具体解决办法参见 #14

**Comment by cheng-kang** [comment]
Duplicate of #16

**Comment by cheng-kang** [comment]
@lniwn 该问题已在 `v0.3.1` 修复。

如果你是从 unpkg 加载 `wildfire` 的话，问题应该会自动消除。
