### ISSUE TITLE
pageURL字段值包含中文字段导致wildfire一直处于加载中

### ISSUE THREAD

**Issue by lniwn** [cheng-kang/wildfire#14]
### 怎么了 What

pageURL字段值包含中文或者其他非标准url字段，会导致wildfire一直处于加载中
![_20171227141530](https://user-images.githubusercontent.com/3256188/34372961-3c1e9a32-eb13-11e7-855b-14883c82e167.png)
![_20171227141457](https://user-images.githubusercontent.com/3256188/34372962-3c493a3a-eb13-11e7-813b-de4f90ce8555.png)
![_20171227141837](https://user-images.githubusercontent.com/3256188/34372964-415a9e92-eb13-11e7-9872-704dfd8c5494.png)

### 如何重现 Reproduce

1. Hexo的Next主题下，设置`pageURL: '{{page.permalink}}'`
2. 文章标题包含中文

### 其他的话 Other Comment

现在的临时解决方案是，在swig层对url进行编码`pageURL: '{{page.permalink|url_encode}}'`，具体可以参考[我的博客](https://blog.oaoa.me/vps/2017/12/%E4%B8%BAHexo%E5%8D%9A%E5%AE%A2Next%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0Wildfire%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F/#%E9%81%87%E5%88%B0%E7%9A%84%E5%9D%91)。
但还是觉得sdk层应该对这种不可信url进行编码之后再处理比较好。

**Comment by mrliaocn** [comment]
感谢你的反馈，刚刚也有人反馈过这个问题，我们会立即修正!

**Comment by mrliaocn** [comment]
这个问题的原因是`btoa`不支持中文造成的。@lniwn 在bug修复前，你可以将设置修改为：
```
pageURL:  location.href 
// location.href 会自动将地址中的中文进行编码转换。
```
来修正这个错误，后面我们在修正时也会兼容这种用法。
预期修正方法见下面一条。

**Comment by mrliaocn** [comment]
@cheng-kang 可以强制将`url`进行`urlencode`, 从而避免中文问题
```
 btoa(encodeURIComponent(url))
```

**Comment by cheng-kang** [comment]
找到了 MDN 对于这个问题的描述以及推荐解决方案。我会采用方案一，然后尽快提交一个新版本。

The issue and solution recommendation.

[The "Unicode Problem" - Base64 encoding and decoding - MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem)

**Comment by cheng-kang** [comment]
请参考 #16 。

Please refer to #16 .

**Comment by cheng-kang** [comment]
Duplicate of #16

**Comment by cheng-kang** [comment]
Fixed in [0d89379](https://github.com/cheng-kang/wildfire/commit/0d89379f57f92911828581c7bc4407a2b5d7b3eb)
