### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jerry011235** [cheng-kang/wildfire#27]
1.增加一个hexo的jade主题添加wildfire的wiki（ejs和swig都有了，就剩jade/pug了）。
2.希望增加一个评论的样式，即传统的昵称、邮箱、网站（可选）、评论内容 这个样式。
当然，作为评论管理者，可以随时切换现有的登陆样式还是传统样式，只是给大家多一个选择罢了。

**Comment by cheng-kang** [comment]
感谢建议，我们会针对这两个建议进行讨论的。

**Comment by cheng-kang** [comment]
@jerry011235 请问你能提供一个使用了 Jade 的 Hexo 主题的链接吗？

@mrliaocn 周末有没有空写一个在使用 Jade 的 Hexo 主题中添加 `wildfire` 的示例？

**Comment by jerry011235** [comment]
@cheng-kang 使用了 Jade 的 Hexo 主题:[maupassant-hexo](https://github.com/tufu9441/maupassant-hexo)

**Comment by mrliaocn** [comment]
@cheng-kang 可以。

**Comment by mrliaocn** [comment]
@jerry011235 项目的`wiki` 已经更新了，设置方法请参考[如何将-Wildfire-添加到-Hexo-博客# jade(pug)模板](https://github.com/cheng-kang/wildfire/wiki/%E5%A6%82%E4%BD%95%E5%B0%86-Wildfire-%E6%B7%BB%E5%8A%A0%E5%88%B0-Hexo-%E5%8D%9A%E5%AE%A2%EF%BC%9F#3-jadepug%E6%A8%A1%E6%9D%BF%E4%BB%A5maupassant%E4%B8%BA%E4%BE%8B)，如果有遇到其他的问题，欢迎继续继续和我们交流~😀

**Comment by jerry011235** [comment]
@cheng-kang 好的，谢谢，还有第二个建议呢：传统的昵称、邮箱、网站（可选）、评论内容 这个样式？

**Comment by cheng-kang** [comment]
@jerry011235 这个我们需要进一步讨论才能做决定。

目前我们在做一个大版本的更新，大概会在这个更新完成之后再回头来考虑这一点。
