### ISSUE TITLE
如何接入野狗的数据库？我无法像firebase一样轻易的找到databaseConfig

### ISSUE THREAD

**Issue by UzkiS** [cheng-kang/wildfire#28]
### 问题描述
找不到野狗的databaseconfig

### 其他的话 Other Comment

野狗已经配置好了，就是找不到它的databaseConfig在哪里获得

**Comment by cheng-kang** [comment]
请进入你的野狗应用的实时通信引擎控制台。进去之后你就能看到 `SyncAppID `，把它复制下来就好了。

在配置 `wildfire` 野狗的配置时，databaseConfig 的内容是类似这样：
```
    databaseConfig: {
      siteId: 'wd2168973289ifdmcg'
    },
```

也可以参考这个例子：https://jsfiddle.net/CHENGKANG/99q5oow4/
