### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by ghost** [cheng-kang/wildfire#39]

**Comment by cheng-kang** [comment]
My guess is that maybe you forgot to add `<div class="wildfire_thread"></div>` to your HTML before `wildfire` script tag.

Could you copy & paste your whole config here so I could have a further look?

**Comment by undef** [comment]
It loads up and works but when posted anonymously
it failed to comment but then adds it 
i think its something related to service workers & there were errors until i pwa-fied it

**Comment by cheng-kang** [comment]
Is the problem solved?
