### ISSUE TITLE
请问在Jekyll NexT中如何部署wildfire评论系统？

### ISSUE THREAD

**Issue by qnscholar** [cheng-kang/wildfire#40]
wildfire看起来不错，不过现在的教程都是基于Hexo NexT主题的，我尝试把wildfire安装到自己的Jekyll NexT系统。按照[这篇教程](https://blog.fushily.cn/2018/03/21/在Hexo博客-NexT主题中部署Wildfire评论系统/#more)，我修改了`/_includes/_partials/comments.html`文件，并把`theme.`换成了`site.`。在.config.yml中也按照教程增加了配置代码。不过编译不通过...想知道哪位大神知道什么原因？谢谢啦

**Comment by cheng-kang** [comment]
能不能把编译不通过的错误信息复制粘贴过来给我看一下？

**Comment by qnscholar** [comment]
我直接在GitHub Desktop提交的代码，后台settings里提示错误，试了好几次都不行。应该是Jekyll 和Hexo的配置方式有些差异。不过，其他很多插件，我照着hexo的教程都能顺利移植到jekyll中，但是wildfire就是没通过。你可以下载[Jekyll NexT](https://github.com/Simpleyyt/jekyll-theme-next)的源码试一试。希望能帮忙解决下问题，很想用wildfire...谢啦

**Comment by cheng-kang** [comment]
麻烦把提示的错误截图给我看一下。

**Comment by cheng-kang** [comment]
@iseex 你好，我刚刚 fork 了 Jekyll NexT 并添加了 wildfire 支持。提交了一个 [PR](https://github.com/Simpleyyt/jekyll-theme-next/pull/93) 不知道会不会被采纳。

如果你没有修改其它源码的话，可以直接下载 https://github.com/wildfirejs/jekyll-theme-next 配置使用。

如果你有已经有其它改动的话，可以参考这个 [commit](https://github.com/wildfirejs/jekyll-theme-next/commit/f304f30d95af9f9f115f4813d41824c934e15747) 对你本地的源码进行修改然后配置使用。
