### ISSUE TITLE
有时掉线，开了vpn全局模式才能正常启动。

### ISSUE THREAD

**Issue by qnscholar** [cheng-kang/wildfire#41]
## 问题描述 Issue Description
刚部署好wildfire到jekyll NexT（首先感谢@[cheng-kang](https://github.com/cheng-kang)）。不过发现一些问题，最大的问题是今天如果不开VPN的全局模式，wildfire就无法启动，我在国内。我在we are using wildfire! 打开其他人的博客，包括开发者cheng-kang 的也是无法启动。会不是firebase在国内的连接不太稳定。请问有啥解决办法吗？thanks!

**Comment by cheng-kang** [comment]
firebase 在国内几乎是不能使用的，因为是 Google 的服务可能被屏蔽了。我在国外所以我自己用的 firebase。

国内建议使用野狗 wilddog。

**Comment by qnscholar** [comment]
野狗我也试过注册账号，不过不知道为啥验证邮件一直收不到，点击再次发送，或者换邮箱，都不行，请问知道什么原因吗？thanks




    



    
    
    


    
        
            
                
                    
                            
                                
                            
                            
                                iseexuhs
                            
                            
                                
                            
                    
                        
                            
                                    浙江大学
                                    iseexuhs@zju.edu.cn
                            
                        
                
            
        
    

签名由 网易邮箱大师 定制


在2018年08月24日 15:41，程康 写道： firebase 在国内几乎是不能使用的，因为是 Google 的服务可能被屏蔽了。
国内建议使用野狗 wilddog。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cheng-kang/wildfire","title":"cheng-kang/wildfire","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cheng-kang/wildfire"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cheng-kang in #41: firebase 在国内几乎是不能使用的，因为是 Google 的服务可能被屏蔽了。\r\n\r\n国内建议使用野狗 wilddog。"}],"action":{"name":"View Issue","url":"https://github.com/cheng-kang/wildfire/issues/41#issuecomment-415679403"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cheng-kang/wildfire/issues/41#issuecomment-415679403",
"url": "https://github.com/cheng-kang/wildfire/issues/41#issuecomment-415679403",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [cheng-kang/wildfire] 有时掉线，开了vpn全局模式才能正常启动。 (#41)",
"sections": [
{
"text": "",
"activityTitle": "**程康**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@cheng-kang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"cheng-kang/wildfire\",\n\"issueId\": 41,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"cheng-kang/wildfire\",\n\"issueId\": 41\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/cheng-kang/wildfire/issues/41#issuecomment-415679403"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371914885\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ihoey** [comment]
@iseex  野狗现在已经停止注册了，目前开放时间还不确定，现在邮件服务是不可用的，别的功能正常

**Comment by qnscholar** [comment]
好吧，那就尴尬了😅，好不容易配置好了还不能用，有点遗憾。不过还是给你们的项目点赞！

**Comment by cheng-kang** [comment]
😅
