### ISSUE TITLE
无法显示成功登录后的信息

### ISSUE THREAD

**Issue by real-re** [cheng-kang/wildfire#43]
### 更换 最新0.5.6 Dev wildfire后 依旧 无法显示成功登录后的信息

HUGO 驱动的 https://narutosenki.top/contact 个人测试网站，看了作者大大 网页框架是0.5.6 我就全都复制过来，`改下自己的firebase key 依旧和之前使用老版本（使用Vue）wildfire评论系统 一样情况`----可以提示登录成功，但之后和没登录的界面一样，只能匿名发言，firebase 配置也是dev rules，数据也能看到，不知是哪里出错了......研究10多个小时无果，前来求助--（浏览器-->chrome+vpn插件）

### 如果大佬就时间

麻烦帮我看看，在下感激不尽

**Comment by cheng-kang** [comment]
![screen shot 2018-09-14 at 09 24 44](https://user-images.githubusercontent.com/8396515/45538843-0cdb2780-b800-11e8-91b3-89e5272a1d2d.png)

刚刚试了一下，好像是可以正常登陆的。请确认一下是不是 VPN 的问题？因为 Firebase 的服务在国内好像不太好使。

但是现在还有一个已知 bug https://github.com/wildfirejs/wildfire-comment/issues/1 我还没来得急修复，尽量今晚回去就改，到时候也会在这里跟你说一下。

**Comment by ReaperOfBlack** [comment]
> ![screen shot 2018-09-14 at 09 24 44](https://user-images.githubusercontent.com/8396515/45538843-0cdb2780-b800-11e8-91b3-89e5272a1d2d.png)
> 
> 刚刚试了一下，好像是可以正常登陆的。请确认一下是不是 VPN 的问题？因为 Firebase 的服务在国内好像不太好使。
> 
> 但是现在还有一个已知 bug [wildfirejs/wildfire-comment#1](https://github.com/wildfirejs/wildfire-comment/issues/1) 我还没来得急修复，尽量今晚回去就改，到时候也会在这里跟你说一下。

谢谢您的反馈 我会继续支持你们的 我再去试试

**Comment by real-re** [comment]
感谢作者大大 急速回复，我会一直支持你们的，谢谢啦

**Comment by real-re** [comment]
1. 大佬 有点尴尬 我的两个firebase管理员邮箱 注册都不能正常显示，寻思试下您的邮箱，目测密码应该不难，结果第一次123456就成功了，果然成功登陆。

2. 我再换个邮箱试试应该就没有问题，可能是管理员规则部分出点问题，（试着在数据库手动添加自己，也可以显示登录）
![tim 20180914195524](https://user-images.githubusercontent.com/43136644/45548801-34f67500-b858-11e8-8b30-dc9e8594bad9.png)

**Comment by cheng-kang** [comment]
@ReaperOfBlack 我想起来之前有这么一个 bug https://github.com/cheng-kang/wildfire/issues/25

如果你能把错误信息截图或者复制过来给我看一下，说不定能想办法解决这个问题。

**Comment by real-re** [comment]
@cheng-kang 我是先注册 后改的最新规则，再登录，导致没有录入数据，所以只会提示登录成功，而没有界面，
1. 其他邮箱注册一下，仿着结构自己填
2. 或者删了自己已注册的邮箱再注册应该就好了
3. 大概再js里添加这种错误的处理逻辑应该就没问题了

修了大半天网页bug，想要鸣谢网站，结果到了wildfire尴尬了 只有一团火，下载svg，svg在线编辑，强行撸出个logo
![logo-4](https://user-images.githubusercontent.com/43136644/45583244-d29d8300-b8f0-11e8-8a65-9c05b9e07408.png)

**Comment by cheng-kang** [comment]
wildfire 的 logo 就是这团火。

**Comment by cheng-kang** [comment]
我在相关 bug 的 issue 里面应引用了你的回复，之后看能不能解决好这个问题。

**Comment by real-re** [comment]
恩
