### ISSUE TITLE
野狗已经不开放注册了，现在Firebase 安全规则不能用 [这个](https://github.com/cheng-kang/wildfire/blob/master/security_rules.json) 给的规则配置了，要怎么配置？

### ISSUE THREAD

**Issue by zsdycs** [cheng-kang/wildfire#45]
Firebase 安全规则不能用json配置了而且野狗已经不开放注册，Firebase 安全规则要怎么配置？  
野火依赖的数据库可以自己建吗，可以说一下思路吗？ 
[可以出一篇关于hugo的教程吗？]

**Comment by zsdycs** [comment]
[这个](https://github.com/cheng-kang/wildfire/blob/master/security_rules.json)

**Comment by zsdycs** [comment]
已经找到了PPT上的规则设置的地方了，Google默认推荐使用``beta``的新的实时数据库需要切换1[这样](https://s2.ax1x.com/2019/01/25/kmFa8S.png)

**Comment by cheng-kang** [comment]
野狗的问题我们已经注意到了。之后应该不会再支持野狗了。

我尝试过搭建一个自己的 Firebase，但是还没有成功😅。思路是按照 Firebase 的 API 写一个后台应用、一个客户端 js 库，用 WebSocket 连接；数据库可以用 CouchDB。

感谢提醒。不过虽然是推荐，但是跟使用现在的数据库不冲突，没有看到会完全放弃现有数据库的迹象。
