### ISSUE TITLE
短信实名功能

### ISSUE THREAD

**Issue by ivmm** [cheng-kang/wildfire#7]
## 问题描述 Issue Description

提供一个短信验证的功能

虽然知道会被喷，但是国内环境必须有一个实名的姿势，可以对接一些短信服务的API

### 怎么了 What

[讲讲问题是什么。]
《互联网跟帖评论服务管理规定》

**Comment by cheng-kang** [comment]
明白😂
但是目前还没有打算呢

不过两个 Firebase 和 野狗好像都有相关的服务。

**Comment by ivmm** [comment]
我也很好奇，明明都有短信服务，为什么不整合进去。

现在没打算可以列入 roadmap ~~

**Comment by cheng-kang** [comment]
在最开始就计划的不要实名，给人添麻烦，觉得有举报功能就够了。除非有人找我们喝茶，那到时候这个项目就废弃了😂

**Comment by cheng-kang** [comment]
这个 issue 暂时先关闭了，感谢提出。
